require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 6.0
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "lib/tasks/cucumber.rake"
    - "sandbox/**/*"
    - "public/dispatch.rb"

Rails:
  Enabled: true

# TODO: remove this
Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false
  Exclude:
    - "config/routes.rb"

Bundler/OrderedGems:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r
  AllowInnerSlashes: false
  Exclude:
    - "features/**/*"

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - "features/**/*"

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Rails/SkipsModelValidations:
  Exclude:
    - "db/migrate/*"

Naming/MethodParameterName:
  Enabled: false

# TODO: review these
RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - "spec/**/*"
