version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd ui
      - npm install
  build:
    commands:
      - echo Building...
      - REACT_APP_STAGE=$STAGE npm run s3deploy
  post_build:
    commands:
      - COMMIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - zip -r /tmp/deploy-${COMMIT_SHA}.zip build/
      - aws s3 cp /tmp/deploy-${COMMIT_SHA}.zip s3://${ARTIFACTS_BUCKET}/${STAGE}/deploy-${COMMIT_SHA}.zip
      - echo "Artifact saved ${STAGE}/deploy-${COMMIT_SHA}.zip"
