version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd ui
      - npm install
  build:
    commands:
      - echo Building.........
      - echo Bucket name---------
      - echo $BUCKET_NAME
      - npm run s3deploy
