/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _not_foundRouteImport } from './routes/__not_found'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsReportIdRouteImport } from './routes/reports/$reportId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as ReportsNewProjectIdRouteImport } from './routes/reports/new/$projectId'
import { Route as ProjectsNewClientIdRouteImport } from './routes/projects/new/$clientId'

const _not_foundRoute = _not_foundRouteImport.update({
  id: '/__not_found',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsNewProjectIdRoute = ReportsNewProjectIdRouteImport.update({
  id: '/reports/new/$projectId',
  path: '/reports/new/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewClientIdRoute = ProjectsNewClientIdRouteImport.update({
  id: '/projects/new/$clientId',
  path: '/projects/new/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/projects/new/$clientId': typeof ProjectsNewClientIdRoute
  '/reports/new/$projectId': typeof ReportsNewProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/projects/new/$clientId': typeof ProjectsNewClientIdRoute
  '/reports/new/$projectId': typeof ReportsNewProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__not_found': typeof _not_foundRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/projects/new/$clientId': typeof ProjectsNewClientIdRoute
  '/reports/new/$projectId': typeof ReportsNewProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients/$clientId'
    | '/projects/$projectId'
    | '/reports/$reportId'
    | '/projects/new/$clientId'
    | '/reports/new/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients/$clientId'
    | '/projects/$projectId'
    | '/reports/$reportId'
    | '/projects/new/$clientId'
    | '/reports/new/$projectId'
  id:
    | '__root__'
    | '/'
    | '/__not_found'
    | '/clients/$clientId'
    | '/projects/$projectId'
    | '/reports/$reportId'
    | '/projects/new/$clientId'
    | '/reports/new/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _not_foundRoute: typeof _not_foundRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  ProjectsNewClientIdRoute: typeof ProjectsNewClientIdRoute
  ReportsNewProjectIdRoute: typeof ReportsNewProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__not_found': {
      id: '/__not_found'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _not_foundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/new/$projectId': {
      id: '/reports/new/$projectId'
      path: '/reports/new/$projectId'
      fullPath: '/reports/new/$projectId'
      preLoaderRoute: typeof ReportsNewProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new/$clientId': {
      id: '/projects/new/$clientId'
      path: '/projects/new/$clientId'
      fullPath: '/projects/new/$clientId'
      preLoaderRoute: typeof ProjectsNewClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _not_foundRoute: _not_foundRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ReportsReportIdRoute: ReportsReportIdRoute,
  ProjectsNewClientIdRoute: ProjectsNewClientIdRoute,
  ReportsNewProjectIdRoute: ReportsNewProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
