default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: mercury_analytics_api_development

test:
  <<: *default
  database: mercury_analytics_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= Rails.application.credentials[:database][:RDS_DB_NAME] %>
  username: <%= Rails.application.credentials[:database][:RDS_USERNAME] %>
  password: <%= Rails.application.credentials[:database][:RDS_PASSWORD] %>
  host: <%= Rails.application.credentials[:database][:RDS_HOSTNAME] %>
  port: <%= Rails.application.credentials[:database][:RDS_PORT] %>
